#!/usr/bin/env bash
# This script displays information about subdomains.

get_domain_info () {
    local main_domain = "$1"
    local subdomain = "$2"
    
    local line=$(dig "${subdomain}.${main_domain}" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "${subdomain} ${line}" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ];
then
    main_domain = "$1"
    
    get_domain_info "$main_domain" "www"
    get_domain_info "$main_domain" "lb-01"
    get_domain_info "$main_domain" "web-01"
    get_domain_info "$main_domain" "web-02"
elif [ "$#" == 2 ];
then
    main_domain = "$1"
    subdomain = "$2"
    
    get_domain_info "$main_domain" "$subdomain"
fi
