#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server as a load balancer.

sudo apt-get -y update
sudo apt-get -y install haproxy=1.6.\*

frontend  Geeorgina
        bind *:80
        mode http
        default_backend web_servers
backend ehoneah-backend
        balance roundrobin
        server 443869-web-01 100.26.165.177:80 check
        server 443869-web-01 100.26.165.177:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Restart Haproxy service
sudo service haproxy restart
