#!/usr/bin/env bash
# This finds out why Ubuntu container’s Nginx installation from listening on port 80

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
