#!/usr/bin/env bash
# Bash script is hort and sweet, 7 lines long or less
pkill apache2
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
